#!/usr/bin/env bash
# Bundles an Edge Function for deploy.
#
# Local layout is per docs/api-integration.md ("Edge Function structure"):
#   supabase/functions/_shared/{cors,supabase,perfectcorp,gemini,prompts,schemas}.ts
#   supabase/functions/<name>/index.ts  (imports from ../_shared/...)
#
# Supabase deploys ONE bundle per function. This script concatenates the
# shared modules and the entrypoint, stripping cross-module local imports,
# and writes the result to dist/edge-functions/<name>.ts for upload.
#
# Usage: scripts/build-edge-function.sh <function-name>

set -euo pipefail

NAME="${1:?usage: build-edge-function.sh <function-name>}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHARED="$ROOT/supabase/functions/_shared"
ENTRY="$ROOT/supabase/functions/$NAME/index.ts"
OUT_DIR="$ROOT/dist/edge-functions"
OUT="$OUT_DIR/$NAME.ts"

if [[ ! -f "$ENTRY" ]]; then
  echo "error: $ENTRY not found" >&2
  exit 1
fi

# Inputs needed per function. Order matters: dependencies first.
case "$NAME" in
  remove-background)
    MODULES=(cors.ts supabase.ts perfectcorp.ts schemas.ts)
    ;;
  extract-ingredients)
    MODULES=(cors.ts supabase.ts gemini.ts prompts.ts schemas.ts)
    ;;
  analyze-skin)
    MODULES=(cors.ts supabase.ts perfectcorp.ts schemas.ts)
    ;;
  analyze-skin-tone)
    MODULES=(cors.ts supabase.ts perfectcorp.ts schemas.ts)
    ;;
  generate-verdict)
    MODULES=(cors.ts supabase.ts gemini.ts prompts.ts schemas.ts)
    ;;
  generate-look)
    MODULES=(cors.ts supabase.ts gemini.ts perfectcorp.ts prompts.ts schemas.ts)
    ;;
  try-from-web)
    MODULES=(cors.ts supabase.ts gemini.ts perfectcorp.ts)
    ;;
  *)
    echo "error: unknown function '$NAME' — add its modules to this script" >&2
    exit 1
    ;;
esac

mkdir -p "$OUT_DIR"

# strip_local_imports: remove single-line imports that point at local files
# (./foo.ts, ../foo.ts) since those files are being inlined. Keep jsr:/npm:.
strip_local_imports() {
  # Pre-condition: every local import is on one line and ends with ".ts";
  # holds for all current modules.
  sed -E '/^import .* from "(\.\.?\/)[^"]*\.ts";$/d; /^import "(\.\.?\/)[^"]*\.ts";$/d'
}

{
  echo "// AUTO-GENERATED by scripts/build-edge-function.sh — do not edit."
  echo "// Source: supabase/functions/_shared/*.ts + supabase/functions/$NAME/index.ts"
  echo ""
  for m in "${MODULES[@]}"; do
    echo "// ----- _shared/$m -----"
    strip_local_imports < "$SHARED/$m"
    echo ""
  done
  echo "// ----- $NAME/index.ts -----"
  strip_local_imports < "$ENTRY"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
